config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :products , only: [:index, :new, :update, :destroy, :create, :show, :edit]
  resources :affiliates, only: [:index, :new, :update, :destroy, :create, :show, :edit]

end

app/models/affiliate.rb
class Affiliate < ApplicationRecord
    def self.query
        @url=Affiliate.find_by_category("tienda").url
        @response = RestClient.get(@url)
        @response =JSON.parse(@response.body)
        return @response
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  store       :string
#  name        :string
#  description :string
#  price       :integer
#  quantity    :integer
#  category    :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ApplicationRecord
    #enum category: {clothes: 0}
end

app/controllers/affiliates_controller.rb
class AffiliatesController < ApplicationController
    skip_before_action :verify_authenticity_token

  def index
    @affiliate = Affiliate.query
    render json: @affiliate
  end

  def new
    @affiliate = Affiliate.new
  end

  def create
    @affiliate = Affiliate.new(affiliate_params)
    if @affiliate.save
      puts "hola"
      redirect_to affiliates_path
    else
      render new, notice: 'no se pudo enviar el fomulario'
    end
  end

private

  def affiliate_params
    params.require(:affiliate).permit(:name,:category, :url)
  end

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  skip_before_action :verify_authenticity_token
  def index
    @product = Product.all
    #render json: @product
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      puts "hola"
      redirect_to products_path
    else
      render new, notice: 'no se pudo enviar el fomulario'
    end
  end

  def show
    @product
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_path, notice: 'el producto ha sido eliminado.' }
    end
  end

  def edit
    @product
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  private

  def product_params
    params.require(:product).permit(:store, :name, :description, :price, :quantity, :category)
    # falta inmagen
  end

  def find_product
    @product = Product.find_by(id: params[:id])
  end
end

app/helpers/affiliates_helper.rb
module AffiliatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/affiliates/new.html.haml
.form1
  = form_with model: @affiliate, local: true do |form|
    .field
      = form.label :name
      = form.text_field :name
    .field
      = form.label :category
      = form.text_field :category
    .field
      = form.label :url
      = form.text_field :url
    .field
      = form.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MarketPlace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/products/index.html.haml
%h1 Product List

%table{:border => 3}
  %tbody
    %tr
      %th Store
      %th Name
      %th Description
      %th Price
      %th Quantity
      %th Category
    - @product.each do |object|
      %tr
        %td= object.store
        %td= object.name
        %td= object.description
        %td= object.price
        %td= object.quantity
        %td= object.category
        %td= link_to 'Show', object
        %td= link_to 'Edit', edit_product_path(object)
        %td= link_to 'Destroy', object, method: :delete, data: { confirm: 'Are you sure?' }


%br/

= link_to('New Product', new_product_path) 

app/views/products/new.html.haml
.form1
  = form_with model: @product, local: true do |form|
    .field
      = form.label :store
      = form.text_field :store
    .field
      = form.label :name
      = form.text_field :name
    .field
      = form.label :description
      = form.text_area :description
    .field
      = form.label :price
      = form.number_field :price
    .field
      = form.label :quantity
      = form.number_field :quantity
    .field
      = form.label :category
      = form.text_field :category 
    .field
      = form.submit

-#   GUSTAVO PA